Repository agentscope-ai/agentscope, pull requests merged in 2024-04, with the labels that each got.

#129 docs: fix error typo
  docs/sphinx_doc/zh_CN/source/tutorial/101-agentscope.md
Labels: documentation

#128 Add agent_id for each agent instance
  src/agentscope/agents/agent.py
  src/agentscope/rpc/__init__.py
  tests/agent_test.py
Labels: feature, ready for review

#136 Update ReActAgent for qwen and other models
  docs/sphinx_doc/en/source/tutorial/206-prompt.md
  docs/sphinx_doc/zh_CN/source/tutorial/206-prompt.md
  examples/conversation_with_react_agent/main.ipynb
  examples/distributed_basic/README.md
  examples/distributed_debate/README.md
  examples/distributed_search/README.md
  examples/game_gomoku/code/gomoku_agent.py
  src/agentscope/agents/dict_dialog_agent.py
  src/agentscope/agents/react_agent.py
  src/agentscope/message.py
  src/agentscope/models/__init__.py
  src/agentscope/models/dashscope_model.py
  src/agentscope/models/gemini_model.py
  src/agentscope/models/model.py
  src/agentscope/models/ollama_model.py
  src/agentscope/models/openai_model.py
  src/agentscope/models/post_model.py
  src/agentscope/models/response.py
  tests/format_test.py
  tests/model_test.py
  tests/prompt_engine_test.py
  tests/web_digest_test.py
Labels: enhancement, ready for review

#94 Support agent_id in agent server
  notebook/distributed_debate.ipynb
  src/agentscope/agents/agent.py
  src/agentscope/agents/rpc_agent.py
  src/agentscope/message.py
  src/agentscope/rpc/__init__.py
  src/agentscope/rpc/rpc_agent.proto
  src/agentscope/rpc/rpc_agent_client.py
  src/agentscope/rpc/rpc_agent_pb2.py
  src/agentscope/rpc/rpc_agent_pb2_grpc.py
  src/agentscope/utils/logging_utils.py
  tests/rpc_agent_test.py
Labels: enhancement, feature, ready for review

#146 Fix Dashscope total_token calculation
  src/agentscope/models/dashscope_model.py
Labels: bug, ready for review

#142 Fix typos in scripts and update README.md
  README.md
  README_ZH.md
  scripts/README.md
  scripts/ollama/model_config.json
Labels: bug, documentation, ready for review

#148 Add arxiv_search service function
  setup.py
  src/agentscope/service/__init__.py
  src/agentscope/service/web_search/arxiv.py
  tests/web_search_test.py
Labels: ready for review, new service

#147 Fix "File exists error" when multiple agents are called at the same time
  src/agentscope/agents/rpc_agent.py
  src/agentscope/file_manager.py
  src/agentscope/message.py
  src/agentscope/utils/logging_utils.py
  src/agentscope/utils/monitor.py
  tests/rpc_agent_test.py
Labels: bug, ready for review

#151 [HOTFIX] Allow the response from ollama doesn't have token counts.
  src/agentscope/models/ollama_model.py
Labels: bug

#152 [HOTFIX] Support gemini.configure setting in model configuration
  src/agentscope/models/gemini_model.py
Labels: bug, ready for review

#132 Example for nl2sql
  README.md
  README_ZH.md
  examples/conversation_nl2sql/configs/model_configs.json
  examples/conversation_nl2sql/database/concert_singer/schema.sql
  examples/conversation_nl2sql/react_sql.ipynb
  examples/conversation_nl2sql/sql_utils.py
  tests/sql_qeury_test.py
  tests/sql_query_test.py
Labels: ready for review, new example

#157 [Hot fix]Fix bug when dialog agent self.memory is None
  src/agentscope/agents/dialog_agent.py
  src/agentscope/agents/dict_dialog_agent.py
Labels: bug

#140 Add download_from_url service function
  docs/sphinx_doc/en/source/agentscope.service.web.rst
  docs/sphinx_doc/en/source/agentscope.service.web_search.rst
  docs/sphinx_doc/en/source/tutorial/204-service.md
  docs/sphinx_doc/zh_CN/source/agentscope.service.web.rst
  docs/sphinx_doc/zh_CN/source/agentscope.service.web_search.rst
  docs/sphinx_doc/zh_CN/source/tutorial/204-service.md
  examples/distributed_search/answerer_agent.py
  examples/distributed_search/searcher_agent.py
  src/agentscope/service/__init__.py
  src/agentscope/service/web/__init__.py
  src/agentscope/service/web/arxiv.py
  src/agentscope/service/web/download.py
  src/agentscope/service/web/search.py
  src/agentscope/service/web/web_digest.py
  tests/web_search_test.py
Labels: ready for review, new service

#159 Refine files in scripts.
  scripts/README.md
  scripts/fastchat/model_config.json
  scripts/vllm/model_config.json
Labels: ready for review

#114 Add drag-and-drop interface & add implementation of DAG running engine for drag-and-drop module
  .flake8
  .pre-commit-config.yaml
  setup.py
  src/agentscope/web/README.md
  src/agentscope/web/studio/studio.py
  src/agentscope/web/workstation/__init__.py
  src/agentscope/web/workstation/examples/0_two_agent.json
  src/agentscope/web/workstation/examples/1_conversation.json
  src/agentscope/web/workstation/examples/2_msghub.json
  src/agentscope/web/workstation/examples/3_condition_pipeline.json
  src/agentscope/web/workstation/examples/4_copiednode.json
  src/agentscope/web/workstation/workflow.py
  src/agentscope/web/workstation/workflow_utils.py
Labels: feature, ready for review

#162 Optimize the structure of Sphinx API doc
  .github/workflows/sphinx_docs.yml
  docs/README.md
  docs/sphinx_doc/build_sphinx_doc.sh
  docs/sphinx_doc/en/source/agentscope.agents.rst
  docs/sphinx_doc/en/source/agentscope.memory.rst
  docs/sphinx_doc/en/source/agentscope.models.rst
  docs/sphinx_doc/en/source/agentscope.pipelines.rst
  docs/sphinx_doc/en/source/agentscope.rpc.rst
  docs/sphinx_doc/en/source/agentscope.rst
  docs/sphinx_doc/en/source/agentscope.service.execute_code.rst
  docs/sphinx_doc/en/source/agentscope.service.file.rst
  docs/sphinx_doc/en/source/agentscope.service.retrieval.rst
  docs/sphinx_doc/en/source/agentscope.service.rst
  docs/sphinx_doc/en/source/agentscope.service.sql_query.rst
  docs/sphinx_doc/en/source/agentscope.service.text_processing.rst
  docs/sphinx_doc/en/source/agentscope.service.web.rst
  docs/sphinx_doc/en/source/agentscope.utils.rst
  docs/sphinx_doc/en/source/agentscope.web.rst
  docs/sphinx_doc/en/source/conf.py
  docs/sphinx_doc/en/source/tutorial/206-prompt.md
  docs/sphinx_doc/template/package.rst_t
  docs/sphinx_doc/zh_CN/source/agentscope.agents.rst
  docs/sphinx_doc/zh_CN/source/agentscope.memory.rst
  docs/sphinx_doc/zh_CN/source/agentscope.models.rst
  docs/sphinx_doc/zh_CN/source/agentscope.pipelines.rst
  docs/sphinx_doc/zh_CN/source/agentscope.rpc.rst
  docs/sphinx_doc/zh_CN/source/agentscope.rst
  docs/sphinx_doc/zh_CN/source/agentscope.service.execute_code.rst
  docs/sphinx_doc/zh_CN/source/agentscope.service.file.rst
  docs/sphinx_doc/zh_CN/source/agentscope.service.retrieval.rst
  docs/sphinx_doc/zh_CN/source/agentscope.service.rst
  docs/sphinx_doc/zh_CN/source/agentscope.service.sql_query.rst
  docs/sphinx_doc/zh_CN/source/agentscope.service.text_processing.rst
  docs/sphinx_doc/zh_CN/source/agentscope.service.web.rst
  docs/sphinx_doc/zh_CN/source/agentscope.utils.rst
  docs/sphinx_doc/zh_CN/source/agentscope.web.rst
  docs/sphinx_doc/zh_CN/source/conf.py
  src/agentscope/__init__.py
  src/agentscope/agents/__init__.py
  src/agentscope/models/__init__.py
  src/agentscope/models/dashscope_model.py
  src/agentscope/models/model.py
  src/agentscope/pipelines/__init__.py
  src/agentscope/rpc/__init__.py
  src/agentscope/service/__init__.py
  src/agentscope/service/web/web_digest.py
Labels: documentation, ready for review

#163 [Hotfix] Fix bugs when x is None
  examples/conversation_with_langchain/README.md
  src/agentscope/models/dashscope_model.py
  src/agentscope/models/gemini_model.py
  src/agentscope/models/ollama_model.py
Labels: ready for review

#171 [Hot Fix] Raise error when user's request is rejected by OpenAI safety system
  src/agentscope/models/openai_model.py
  src/agentscope/models/post_model.py
Labels: bug, ready for review

#174 fix macos version error
  .github/workflows/unittest.yml
Labels: bug

#164 Add Compiler & Refactor workflow dag runner code
  setup.py
  src/agentscope/web/README.md
  src/agentscope/web/workstation/examples/5_groupchat.json
  src/agentscope/web/workstation/examples/6_reactagent.json
  src/agentscope/web/workstation/workflow.py
  src/agentscope/web/workstation/workflow_dag.py
  src/agentscope/web/workstation/workflow_node.py
  src/agentscope/web/workstation/workflow_utils.py
Labels: enhancement, ready for review

#178 Make workflow compiler return code string
  src/agentscope/web/workstation/workflow_dag.py
  src/agentscope/web/workstation/workflow_node.py
Labels: enhancement

#180 [DOC] Generate .rst for each .py file and add __init__ method into docs
  .github/workflows/sphinx_docs.yml
  docs/sphinx_doc/build_sphinx_doc.sh
  docs/sphinx_doc/en/source/conf.py
  docs/sphinx_doc/en/source/index.rst
  docs/sphinx_doc/template/module.rst_t
  docs/sphinx_doc/template/package.rst_t
  docs/sphinx_doc/zh_CN/source/conf.py
  docs/sphinx_doc/zh_CN/source/index.rst
  src/agentscope/agents/dict_dialog_agent.py
  src/agentscope/message.py
  src/agentscope/msghub.py
  src/agentscope/prompt.py
Labels: documentation

#153 Improve ReActAgent and extract several modules from it
  docs/sphinx_doc/en/source/index.rst
  docs/sphinx_doc/en/source/tutorial/204-service.md
  docs/sphinx_doc/zh_CN/source/index.rst
  docs/sphinx_doc/zh_CN/source/tutorial/204-service.md
  examples/conversation_nl2sql/react_nl2sql.ipynb
  examples/conversation_with_react_agent/code/conversation_with_react_agent.py
  examples/conversation_with_react_agent/main.ipynb
  src/agentscope/__init__.py
  src/agentscope/agents/react_agent.py
  src/agentscope/exception.py
  src/agentscope/models/__init__.py
  src/agentscope/models/model.py
  src/agentscope/models/response.py
  src/agentscope/parsers/__init__.py
  src/agentscope/parsers/code_block_parser.py
  src/agentscope/parsers/json_object_parser.py
  src/agentscope/parsers/parser_base.py
  src/agentscope/parsers/tagged_content_parser.py
  src/agentscope/service/__init__.py
  src/agentscope/service/service_factory.py
  src/agentscope/service/service_toolkit.py
  src/agentscope/service/sql_query/mysql.py
  src/agentscope/service/sql_query/sqlite.py
  src/agentscope/utils/common.py
  src/agentscope/utils/tools.py
  tests/service_factory_test.py
  tests/service_toolkit_test.py
Labels: enhancement, ready for review

#172 Modify flask services
  docs/sphinx_doc/en/source/tutorial/203-model.md
  docs/sphinx_doc/zh_CN/source/tutorial/203-model.md
  examples/model_configs_template/postapi_model_config_template.json
  scripts/README.md
  scripts/flask_modelscope/model_config.json
  scripts/flask_modelscope/setup_ms_service.py
  scripts/flask_transformers/model_config.json
  scripts/flask_transformers/setup_hf_service.py
  src/agentscope/models/post_model.py
  src/agentscope/utils/tools.py
Labels: ready for review

#135 Agent servers support running any type of agent
  README.md
  README_ZH.md
  docs/sphinx_doc/en/source/conf.py
  docs/sphinx_doc/en/source/tutorial/201-agent.md
  docs/sphinx_doc/en/source/tutorial/207-monitor.md
  docs/sphinx_doc/en/source/tutorial/208-distribute.md
  docs/sphinx_doc/zh_CN/source/tutorial/201-agent.md
  docs/sphinx_doc/zh_CN/source/tutorial/207-monitor.md
  docs/sphinx_doc/zh_CN/source/tutorial/208-distribute.md
  examples/distributed_basic/distributed_dialog.py
  examples/distributed_debate/distributed_debate.py
  examples/distributed_simulation/README.md
  examples/distributed_simulation/configs/model_configs.json
  examples/distributed_simulation/main.py
  examples/distributed_simulation/participant.py
  examples/distributed_simulation/run_simlation.sh
  examples/distributed_simulation/start_all_server.sh
  examples/distributed_simulation/start_vllm.sh
  examples/distributed_simulation/stop_all_server.sh
  examples/distributed_simulation/stop_vllm.sh
  setup.py
  src/agentscope/_init.py
  src/agentscope/agents/__init__.py
  src/agentscope/agents/agent.py
  src/agentscope/agents/rpc_agent.py
  src/agentscope/message.py
  src/agentscope/rpc/rpc_agent_client.py
  src/agentscope/utils/monitor.py
  tests/monitor_test.py
  tests/rpc_agent_test.py
Labels: enhancement, feature, ready for review

#191 Minior fix for v0.0.4 release
  README.md
  README_ZH.md
  examples/distributed_debate/distributed_debate.py
  examples/distributed_search/answerer_agent.py
  src/agentscope/_version.py
Labels: ready for review
