Repository agentscope-ai/agentscope, pull requests merged in 2024-02, with the labels that each got.

#18 Refactor Distributed Modules
  .pre-commit-config.yaml
  docs/sphinx_doc/source/agentscope.agents.rst
  docs/sphinx_doc/source/tutorial/201-agent.md
  docs/sphinx_doc/source/tutorial/208-distribute.md
  examples/distributed/configs/debate_agent_configs.json
  examples/distributed/distributed_debate.py
  examples/distributed/distributed_dialog.py
  notebook/distributed_debate.ipynb
  notebook/distributed_dialog.ipynb
  src/agentscope/_init.py
  src/agentscope/agents/__init__.py
  src/agentscope/agents/agent.py
  src/agentscope/agents/rpc_agent.py
  src/agentscope/agents/rpc_dialog_agent.py
  src/agentscope/agents/user_agent.py
  src/agentscope/constants.py
  src/agentscope/message.py
  src/agentscope/models/__init__.py
  src/agentscope/rpc/rpc_agent_client.py
  src/agentscope/utils/logging_utils.py
  tests/rpc_agent_test.py
Labels: enhancement

#23 Saving runtime configuration in root directory automatically
  src/agentscope/_init.py
  src/agentscope/_runtime.py
  src/agentscope/constants.py
  src/agentscope/file_manager.py
  src/agentscope/utils/tools.py
Labels: feature

#27 【WEBUI】Add speak function within AgentBase.
  src/agentscope/agents/agent.py
  src/agentscope/agents/dialog_agent.py
  src/agentscope/agents/dict_dialog_agent.py
  src/agentscope/utils/logging_utils.py
  tests/logger_test.py
Labels: enhancement

#24 Refactor ModelWrapper
  README.md
  docs/sphinx_doc/source/agentscope.agents.rst
  docs/sphinx_doc/source/agentscope.configs.rst
  docs/sphinx_doc/source/agentscope.models.rst
  docs/sphinx_doc/source/index.rst
  docs/sphinx_doc/source/tutorial/103-example.md
  docs/sphinx_doc/source/tutorial/104-usecase.md
  docs/sphinx_doc/source/tutorial/201-agent.md
  docs/sphinx_doc/source/tutorial/203-model.md
  examples/conversation/conversation.py
  examples/distributed/configs/debate_agent_configs.json
  examples/distributed/configs/model_configs.json
  examples/distributed/distributed_dialog.py
  examples/werewolf/README.md
  examples/werewolf/configs/agent_configs.json
  examples/werewolf/configs/model_configs.json
  notebook/conversation.ipynb
  notebook/distributed_debate.ipynb
  notebook/distributed_dialog.ipynb
  scripts/README.md
  scripts/faschat/model_config.json
  scripts/flask_modelscope/model_config.json
  scripts/flask_transformers/model_config.json
  scripts/vllm_script/model_config.json
  src/agentscope/_init.py
  src/agentscope/agents/__init__.py
  src/agentscope/agents/agent.py
  src/agentscope/agents/dialog_agent.py
  src/agentscope/agents/dict_dialog_agent.py
  src/agentscope/agents/text_to_image_agent.py
  src/agentscope/configs/__init__.py
  src/agentscope/configs/model_config.py
  src/agentscope/memory/temporary_memory.py
  src/agentscope/message.py
  src/agentscope/models/__init__.py
  src/agentscope/models/config.py
  src/agentscope/models/model.py
  src/agentscope/models/openai_model.py
  src/agentscope/models/post_model.py
  src/agentscope/service/text_processing/summarization.py
  tests/model_test.py
  tests/monitor_test.py
  tests/prompt_engine_test.py
  tests/record_api_invocation_test.py
  tests/retrieval_from_list_test.py
  tests/rpc_agent_test.py
Labels: enhancement

#31 [Hot fix]Fix parse_func and fault_handler of ModelWrapper
  README.md
  docs/sphinx_doc/source/tutorial/201-agent.md
  docs/sphinx_doc/source/tutorial/204-service.md
  src/agentscope/agents/dict_dialog_agent.py
  src/agentscope/models/model.py
Labels: bug

#33 Add arXiv paper into README.md
  README.md
Labels: documentation

#26 Add ServiceFactory to support quick setup for tools model&agent.
  docs/sphinx_doc/source/agentscope.service.execute_code.rst
  docs/sphinx_doc/source/agentscope.service.rst
  setup.py
  src/agentscope/pipelines/functional.py
  src/agentscope/service/__init__.py
  src/agentscope/service/execute_code/__init__.py
  src/agentscope/service/execute_code/exec_python.py
  src/agentscope/service/retrieval/retrieval_from_list.py
  src/agentscope/service/service_factory.py
  src/agentscope/service/sql_query/mongodb.py
  src/agentscope/service/sql_query/mysql.py
  src/agentscope/service/sql_query/sqlite.py
  src/agentscope/service/text_processing/summarization.py
  src/agentscope/service/web_search/search.py
  tests/service_factory_test.py
  tests/web_search_test.py
Labels: feature
