Repository agentscope-ai/agentscope, pull requests merged in 2024-03, with the labels that each got.

#48 Add win & macos support
  .github/workflows/unittest.yml
  src/agentscope/service/execute_code/exec_python.py
  src/agentscope/utils/common.py
  tests/execute_python_code_test.py
  tests/logger_test.py
Labels: enhancement

#47 Optimize launcher of RPCAgent
  src/agentscope/agents/rpc_agent.py
  src/agentscope/models/model.py
Labels: enhancement

#60 Add ollama based local model services in AgentScope.
  setup.py
  src/agentscope/models/__init__.py
  src/agentscope/models/ollama_model.py
  tests/ollama_test.py
Labels: enhancement

#55 Add groupchat with @ example
  examples/distributed/user_proxy_agent.py
  examples/groupchat/README.md
  examples/groupchat/configs/agent_configs.json
  examples/groupchat/configs/model_configs.json
  examples/groupchat/groupchat_utils.py
  examples/groupchat/main.py
  setup.py
  src/agentscope/agents/user_agent.py
  src/agentscope/utils/common.py
  src/agentscope/web/studio/utils.py
Labels: enhancement, ready_for_review

#59 Add Gemini Chat and Embedding models in AgentScope
  setup.py
  src/agentscope/_runtime.py
  src/agentscope/agents/__init__.py
  src/agentscope/file_manager.py
  src/agentscope/models/__init__.py
  src/agentscope/models/dashscope_model.py
  src/agentscope/models/gemini_model.py
  src/agentscope/models/model.py
  src/agentscope/models/ollama_model.py
  src/agentscope/models/openai_model.py
  src/agentscope/models/post_model.py
  src/agentscope/models/tongyi_model.py
  src/agentscope/service/text_processing/summarization.py
  src/agentscope/utils/logging_utils.py
  src/agentscope/utils/monitor.py
  src/agentscope/utils/tools.py
  tests/gemini_test.py
  tests/ollama_test.py
  tests/record_api_invocation_test.py
Labels: enhancement, ready for review

#76 [Hot Fix]Optimize error messages of ModelWrapper
  src/agentscope/models/dashscope_model.py
  src/agentscope/models/openai_model.py
Labels: enhancement

#62 Add an example for the compatibility with langchain
  examples/conversation_with_langchain/READMD.md
  examples/conversation_with_langchain/conversation_with_langchain.py
Labels: ready for review, add example

#82 Unify model implementation and clean up their code in AgentScope.
  docs/sphinx_doc/en/source/tutorial/203-model.md
  docs/sphinx_doc/en/source/tutorial/206-prompt.md
  docs/sphinx_doc/zh_CN/source/tutorial/206-prompt.md
  src/agentscope/models/__init__.py
  src/agentscope/models/config.py
  src/agentscope/models/dashscope_model.py
  src/agentscope/models/gemini_model.py
  src/agentscope/models/model.py
  src/agentscope/models/ollama_model.py
  src/agentscope/models/openai_model.py
  src/agentscope/models/post_model.py
  src/agentscope/prompt.py
  src/agentscope/service/text_processing/summarization.py
  tests/dashscope_test.py
  tests/model_test.py
  tests/ollama_test.py
  tests/prompt_engine_test.py
Labels: enhancement, ready for review

#81 add AS studio usage in README
  src/agentscope/web/README.md
Labels: documentation

#93 Fix the text_to_image_agent failure when accepting None input
  src/agentscope/agents/text_to_image_agent.py
  src/agentscope/utils/common.py
Labels: bug, ready for review

#95 Fix bug in PromptEngine and provide prompt construction strategy for most chat and generation APIs
  README.md
  docs/sphinx_doc/en/source/tutorial/206-prompt.md
  docs/sphinx_doc/en/source/tutorial/main.md
  docs/sphinx_doc/zh_CN/source/tutorial/206-prompt.md
  examples/conversation_self_organizing/auto-discussion.py
  examples/conversation_with_langchain/conversation_with_langchain.py
  examples/conversation_with_mentions/main.py
  examples/distributed/distributed_debate.py
  examples/game_werewolf/werewolf.py
  examples/game_werewolf/werewolf_utils.py
  src/agentscope/agents/dialog_agent.py
  src/agentscope/agents/dict_dialog_agent.py
  src/agentscope/agents/rpc_agent.py
  src/agentscope/agents/text_to_image_agent.py
  src/agentscope/agents/user_agent.py
  src/agentscope/message.py
  src/agentscope/models/dashscope_model.py
  src/agentscope/models/gemini_model.py
  src/agentscope/models/model.py
  src/agentscope/models/ollama_model.py
  src/agentscope/models/openai_model.py
  src/agentscope/models/post_model.py
  src/agentscope/prompt.py
  src/agentscope/service/text_processing/summarization.py
  src/agentscope/utils/logging_utils.py
  tests/format_test.py
  tests/memory_test.py
  tests/model_test.py
  tests/retrieval_from_list_test.py
  tests/rpc_agent_test.py
Labels: enhancement, ready for review

#100 [HOTFIX] Create a new function to convert content to string.
  src/agentscope/agents/dict_dialog_agent.py
  src/agentscope/models/dashscope_model.py
  src/agentscope/models/gemini_model.py
  src/agentscope/models/ollama_model.py
  src/agentscope/models/openai_model.py
  src/agentscope/models/post_model.py
  src/agentscope/models/tongyi_model.py
  src/agentscope/utils/tools.py
Labels: bug, ready for review

#84 Adding web page digest function to service module
  setup.py
  src/agentscope/service/__init__.py
  src/agentscope/service/text_processing/summarization.py
  src/agentscope/service/web_search/web_digest.py
  tests/web_digest_test.py
Labels: feature, ready for review

#103 Adding gomoku example
  README.md
  README_ZH.md
  examples/game_gomoku/code/board_agent.py
  examples/game_gomoku/code/game_gomoku.py
  examples/game_gomoku/code/gomoku_agent.py
  examples/game_gomoku/main.ipynb
  src/agentscope/agents/agent.py
Labels: add example

#107 Add attr `participants` to pipeline
  src/agentscope/pipelines/pipeline.py
Labels: enhancement, ready for review

#111 Fix typos in tutorial and add link to example model configurations
  README.md
  README_ZH.md
  docs/sphinx_doc/en/source/tutorial/203-model.md
  docs/sphinx_doc/zh_CN/source/tutorial/203-model.md
Labels: documentation, ready for review

#104 Add a ReAct agent and an example conversation with this agent.
  README.md
  README_ZH.md
  docs/sphinx_doc/en/source/agentscope.agents.rst
  docs/sphinx_doc/zh_CN/source/agentscope.agents.rst
  examples/conversation_with_react_agent/code/conversation_with_react_agent.py
  examples/conversation_with_react_agent/main.ipynb
  src/agentscope/agents/__init__.py
  src/agentscope/agents/react_agent.py
  src/agentscope/models/post_model.py
Labels: feature, add example

#115 fix mypy ignore pattern
  examples/distributed/user_proxy_agent.py
  src/agentscope/agents/rpc_agent.py
  src/agentscope/models/__init__.py
  src/agentscope/pipelines/functional.py
  src/agentscope/utils/monitor.py
  tests/monitor_test.py
  tests/rpc_agent_test.py
Labels: bug

#64 Introducing RAG module into package
  README.md
  README_ZH.md
  examples/conversation_with_RAG_agents/README.md
  examples/conversation_with_RAG_agents/agent_config.json
  examples/conversation_with_RAG_agents/rag/__init__.py
  examples/conversation_with_RAG_agents/rag/langchain_rag.py
  examples/conversation_with_RAG_agents/rag/llama_index_rag.py
  examples/conversation_with_RAG_agents/rag/rag.py
  examples/conversation_with_RAG_agents/rag_agents.py
  examples/conversation_with_RAG_agents/rag_example.py
Labels: feature, ready for review

#121 Add distributed search example
  .pre-commit-config.yaml
  README.md
  README_ZH.md
  examples/distributed_basic/README.md
  examples/distributed_basic/configs/model_configs.json
  examples/distributed_basic/distributed_dialog.py
  examples/distributed_debate/README.md
  examples/distributed_debate/configs/debate_agent_configs.json
  examples/distributed_debate/configs/model_configs.json
  examples/distributed_debate/distributed_debate.py
  examples/distributed_debate/user_proxy_agent.py
  examples/distributed_search/README.md
  examples/distributed_search/answerer_agent.py
  examples/distributed_search/configs/model_configs.json
  examples/distributed_search/main.py
  examples/distributed_search/searcher_agent.py
Labels: ready for review, add example

#125 Update sphinx doc for v0.0.2
  README.md
  README_ZH.md
  docs/sphinx_doc/en/source/agentscope.models.rst
  docs/sphinx_doc/en/source/agentscope.service.web_search.rst
  docs/sphinx_doc/en/source/tutorial/102-installation.md
  docs/sphinx_doc/en/source/tutorial/104-usecase.md
  docs/sphinx_doc/en/source/tutorial/201-agent.md
  docs/sphinx_doc/en/source/tutorial/204-service.md
  docs/sphinx_doc/en/source/tutorial/302-contribute.md
  docs/sphinx_doc/zh_CN/source/agentscope.models.rst
  docs/sphinx_doc/zh_CN/source/agentscope.service.web_search.rst
  docs/sphinx_doc/zh_CN/source/tutorial/102-installation.md
  docs/sphinx_doc/zh_CN/source/tutorial/104-usecase.md
  docs/sphinx_doc/zh_CN/source/tutorial/201-agent.md
  docs/sphinx_doc/zh_CN/source/tutorial/204-service.md
  docs/sphinx_doc/zh_CN/source/tutorial/302-contribute.md
  setup.py
  src/agentscope/agents/text_to_image_agent.py
  src/agentscope/models/dashscope_model.py
  src/agentscope/models/post_model.py
  src/agentscope/service/web_search/web_digest.py
Labels: documentation, ready for review
