Repository agentscope-ai/agentscope, pull requests merged in 2024-07, with the labels that each got.

#317 [Hotfix] Fix gradio displaying user message twice
  src/agentscope/agents/user_agent.py
  src/agentscope/logging.py
Labels: bug, ready for review

#314 Unify the typing of the agents' reply function and update their docstrings.
  docs/sphinx_doc/en/source/tutorial/104-usecase.md
  docs/sphinx_doc/en/source/tutorial/201-agent.md
  docs/sphinx_doc/en/source/tutorial/203-parser.md
  docs/sphinx_doc/en/source/tutorial/204-service.md
  docs/sphinx_doc/en/source/tutorial/209-prompt_opt.md
  docs/sphinx_doc/zh_CN/source/tutorial/104-usecase.md
  docs/sphinx_doc/zh_CN/source/tutorial/201-agent.md
  docs/sphinx_doc/zh_CN/source/tutorial/203-parser.md
  docs/sphinx_doc/zh_CN/source/tutorial/204-service.md
  docs/sphinx_doc/zh_CN/source/tutorial/209-prompt_opt.md
  examples/conversation_with_langchain/conversation_with_langchain.py
  examples/conversation_with_swe-agent/swe_agent.py
  examples/distributed_debate/user_proxy_agent.py
  examples/distributed_parallel_optimization/answerer_agent.py
  examples/distributed_parallel_optimization/searcher_agent.py
  examples/distributed_simulation/participant.py
  examples/game_gomoku/code/board_agent.py
  examples/game_gomoku/code/gomoku_agent.py
  examples/game_gomoku/main.ipynb
  src/agentscope/agents/agent.py
  src/agentscope/agents/dialog_agent.py
  src/agentscope/agents/dict_dialog_agent.py
  src/agentscope/agents/rag_agent.py
  src/agentscope/agents/react_agent.py
  src/agentscope/agents/rpc_agent.py
  src/agentscope/agents/text_to_image_agent.py
  src/agentscope/agents/user_agent.py
  src/agentscope/prompt/_prompt_comparer.py
  tests/msghub_test.py
  tests/rpc_agent_test.py
Labels: enhancement, ready for review

#322 Adding an example of setting up local embedding model
  docs/sphinx_doc/en/source/tutorial/210-rag.md
  docs/sphinx_doc/zh_CN/source/tutorial/210-rag.md
Labels: documentation, ready for review

#325 Fix display bug in workstation for group nodes
  src/agentscope/studio/static/js/workstation.js
Labels: bug, AgentScope Studio

#330 [HOTFIX] Remove notebook directory and fix typos.
  examples/conversation_basic/README.md
  notebook/conversation.ipynb
  notebook/distributed_debate.ipynb
  notebook/distributed_dialog.ipynb
Labels: documentation, ready for review

#342 [HOTFIX] Fix bug in DictDialogAgent
  src/agentscope/agents/dict_dialog_agent.py
Labels: bug, ready for review

#346 Add test Module for MoA
  tests/moa_test.py
Labels: ready for review

#239 Add agent server management functions
  docs/sphinx_doc/en/source/tutorial/208-distribute.md
  docs/sphinx_doc/zh_CN/source/tutorial/208-distribute.md
  examples/distributed_debate/distributed_debate.py
  examples/distributed_simulation/main.py
  examples/distributed_simulation/start_all_server.sh
  examples/distributed_simulation/start_vllm.sh
  setup.py
  src/agentscope/agents/agent.py
  src/agentscope/agents/rpc_agent.py
  src/agentscope/constants.py
  src/agentscope/exception.py
  src/agentscope/message.py
  src/agentscope/rpc/rpc_agent.proto
  src/agentscope/rpc/rpc_agent_client.py
  src/agentscope/rpc/rpc_agent_pb2.py
  src/agentscope/rpc/rpc_agent_pb2_grpc.py
  src/agentscope/server/launcher.py
  src/agentscope/server/servicer.py
  src/agentscope/studio/_app.py
  src/agentscope/studio/static/css/server.css
  src/agentscope/studio/static/html/index-guide.html
  src/agentscope/studio/static/html/server.html
  src/agentscope/studio/static/js/index.js
  src/agentscope/studio/static/js/server.js
  src/agentscope/studio/static/svg/circle-add.svg
  src/agentscope/studio/static/svg/circle-delete.svg
  src/agentscope/studio/static/svg/flush.svg
  src/agentscope/studio/static/svg/trash-bin.svg
  src/agentscope/studio/templates/index.html
  src/agentscope/utils/tools.py
  tests/agent_test.py
  tests/data/image.png
  tests/rpc_agent_test.py
Labels: enhancement, ready for review

#350 [HOT FIX]Fix potential bugs in summary function
  src/agentscope/service/text_processing/summarization.py
Labels: bug, ready for review

#347 Support streaming mode in AgentScope
  README.md
  README_ZH.md
  docs/sphinx_doc/en/source/index.rst
  docs/sphinx_doc/en/source/tutorial/203-stream.md
  docs/sphinx_doc/en/source/tutorial/main.md
  docs/sphinx_doc/zh_CN/source/index.rst
  docs/sphinx_doc/zh_CN/source/tutorial/203-stream.md
  docs/sphinx_doc/zh_CN/source/tutorial/main.md
  examples/conversation_basic/conversation.py
  examples/conversation_in_stream_mode/README.md
  examples/conversation_in_stream_mode/main.py
  src/agentscope/agents/agent.py
  src/agentscope/agents/dialog_agent.py
  src/agentscope/agents/dict_dialog_agent.py
  src/agentscope/agents/react_agent.py
  src/agentscope/file_manager.py
  src/agentscope/logging.py
  src/agentscope/message.py
  src/agentscope/models/_model_utils.py
  src/agentscope/models/dashscope_model.py
  src/agentscope/models/gemini_model.py
  src/agentscope/models/litellm_model.py
  src/agentscope/models/ollama_model.py
  src/agentscope/models/openai_model.py
  src/agentscope/models/response.py
  src/agentscope/models/zhipu_model.py
  src/agentscope/studio/_app.py
  src/agentscope/studio/_client.py
  src/agentscope/studio/_studio_utils.py
  src/agentscope/studio/static/js/dashboard-detail-dialogue.js
  src/agentscope/utils/monitor.py
  src/agentscope/utils/tools.py
  tests/dashscope_test.py
  tests/logger_test.py
  tests/record_api_invocation_test.py
  tests/rpc_agent_test.py
Labels: feature, ready for review, AgentScope Studio

#371 [Hot Fix] Fixed script loaded check function in Studio
  src/agentscope/studio/static/js/index.js
Labels: bug
