Repository agentscope-ai/agentscope, pull requests merged in 2024-08, with the labels that each got.

#231 Add notebook executor as service function and add codeact agent.
  README.md
  README_ZH.md
  docs/sphinx_doc/en/source/tutorial/204-service.md
  docs/sphinx_doc/zh_CN/source/tutorial/204-service.md
  examples/conversation_with_codeact_agent/codeact_agent.py
  examples/conversation_with_codeact_agent/codeact_agent_example_modeling.ipynb
  examples/conversation_with_codeact_agent/codeact_agent_example_tools.ipynb
  examples/conversation_with_codeact_agent/linear_regression_plot.png
  setup.py
  src/agentscope/file_manager.py
  src/agentscope/service/__init__.py
  src/agentscope/service/execute_code/exec_notebook.py
  src/agentscope/service/service_toolkit.py
  tests/execute_notebook_code_test.py
Labels: enhancement, ready for review

#351 Studio supports allocation of agent server
  docs/sphinx_doc/en/source/tutorial/208-distribute.md
  docs/sphinx_doc/en/source/tutorial/209-gui.md
  docs/sphinx_doc/zh_CN/source/tutorial/208-distribute.md
  docs/sphinx_doc/zh_CN/source/tutorial/209-gui.md
  src/agentscope/agents/agent.py
  src/agentscope/agents/rpc_agent.py
  src/agentscope/server/launcher.py
  src/agentscope/server/servicer.py
  src/agentscope/studio/_app.py
  src/agentscope/studio/_client.py
  src/agentscope/studio/static/js/server.js
  src/agentscope/utils/tools.py
  tests/custom/custom_agent.py
  tests/custom/utils.py
  tests/rpc_agent_test.py
Labels: enhancement, ready for review

#386 Unify message related typing in AgentScope into Msg rather than dict
  examples/distributed_debate/user_proxy_agent.py
  src/agentscope/agents/agent.py
  src/agentscope/agents/rpc_agent.py
  src/agentscope/logging.py
  src/agentscope/msghub.py
  tests/rpc_agent_test.py
Labels: enhancement, ready for review

#345 Online workstation
  examples/0_jupyter_example_template/main.ipynb
  setup.py
  src/agentscope/constants.py
  src/agentscope/studio/_app.py
  src/agentscope/studio/_app_online.py
  src/agentscope/studio/static/css/login.css
  src/agentscope/studio/static/js/workstation.js
  src/agentscope/studio/static/js_third_party/buttons.js
  src/agentscope/studio/static/js_third_party/sweetalert2@11
  src/agentscope/studio/static/js_third_party/sweetalert2@9
  src/agentscope/studio/templates/login.html
  src/agentscope/studio/templates/workstation.html
  src/agentscope/studio/utils.py
Labels: ready for review

#414 Support running as_gradio for html configs
  src/agentscope/studio/static/js/workstation.js
  src/agentscope/web/workstation/workflow_dag.py
  src/agentscope/web/workstation/workflow_node.py
Labels: ready for review

#416 Add example for router agent
  README.md
  README_ZH.md
  examples/conversation_with_router_agent/README.md
  examples/conversation_with_router_agent/main.py
  examples/conversation_with_router_agent/router_agent.py
Labels: ready for review, new example

#415 Fix the deprecated load_model_by_config_name in the nl2sql example
  examples/conversation_nl2sql/react_nl2sql.ipynb
Labels: ready for review

#388 Support to serialize message objects in AgentScope and remove unused arguments.
  docs/sphinx_doc/en/source/tutorial/201-agent.md
  docs/sphinx_doc/zh_CN/source/tutorial/201-agent.md
  examples/conversation_mixture_of_agents/conversation_moa.py
  examples/conversation_nl2sql/sql_utils.py
  examples/conversation_self_organizing/auto-discussion.py
  examples/conversation_with_RAG_agents/rag_example.py
  examples/conversation_with_mentions/main.py
  examples/conversation_with_swe-agent/swe_agent.py
  examples/distributed_parallel_optimization/answerer_agent.py
  examples/distributed_parallel_optimization/searcher_agent.py
  examples/distributed_simulation/main.py
  examples/distributed_simulation/participant.py
  examples/paper_llm_based_algorithm/src/alg_agents.py
  examples/paper_llm_based_algorithm/src/counting.py
  examples/paper_llm_based_algorithm/src/rag.py
  examples/paper_llm_based_algorithm/src/retrieval.py
  examples/paper_llm_based_algorithm/src/sorting.py
  src/agentscope/agents/agent.py
  src/agentscope/agents/dialog_agent.py
  src/agentscope/agents/dict_dialog_agent.py
  src/agentscope/agents/rag_agent.py
  src/agentscope/agents/rpc_agent.py
  src/agentscope/agents/text_to_image_agent.py
  src/agentscope/agents/user_agent.py
  src/agentscope/logging.py
  src/agentscope/memory/memory.py
  src/agentscope/memory/temporary_memory.py
  src/agentscope/message/__init__.py
  src/agentscope/message/msg.py
  src/agentscope/message/placeholder.py
  src/agentscope/rpc/rpc_agent_client.py
  src/agentscope/serialize.py
  src/agentscope/server/servicer.py
  src/agentscope/service/multi_modality/openai_services.py
  src/agentscope/studio/static/html-drag-components/message-msg.html
  src/agentscope/studio/static/js/workstation.js
  src/agentscope/studio/static/workstation_templates/en4.json
  src/agentscope/test.py
  src/agentscope/utils/tools.py
  tests/agent_test.py
  tests/logger_test.py
  tests/memory_test.py
  tests/message_test.py
  tests/msghub_test.py
  tests/retrieval_from_list_test.py
  tests/rpc_agent_test.py
  tests/serialize_test.py
Labels: enhancement, ready for review

#426 [Hotfix] Fix hyperlinks for online workstation in readme
  README.md
  README_ZH.md
  examples/distributed_conversation/README.md
Labels: ready for review
