Repository agentscope-ai/agentscope, pull requests merged in 2024-05, with the labels that each got.

#181 Add ZhipuAI model wrappers
  README.md
  README_ZH.md
  docs/sphinx_doc/en/source/tutorial/203-model.md
  docs/sphinx_doc/en/source/tutorial/206-prompt.md
  docs/sphinx_doc/zh_CN/source/tutorial/203-model.md
  docs/sphinx_doc/zh_CN/source/tutorial/206-prompt.md
  examples/model_configs_template/zhipu_chat_template.json
  examples/model_configs_template/zhipu_embedding_template.json
  setup.py
  src/agentscope/models/__init__.py
  src/agentscope/models/zhipu_model.py
  tests/format_test.py
  tests/zhipu_test.py
Labels: documentation, enhancement, ready for review

#212 [HOTFIX] Fix bug in board agent
  examples/game_gomoku/code/board_agent.py
  examples/game_gomoku/main.ipynb
Labels: bug, ready for review

#197 [Hotfix] Fix memory loading error
  src/agentscope/memory/memory.py
  src/agentscope/memory/temporary_memory.py
  src/agentscope/message.py
  tests/memory_test.py
  tests/msghub_test.py
Labels: bug, ready for review

#206 [HOTFIX] Update prompt strategy in Ollama chat API.
  docs/sphinx_doc/en/source/tutorial/206-prompt.md
  docs/sphinx_doc/zh_CN/source/tutorial/206-prompt.md
  src/agentscope/models/ollama_model.py
  tests/format_test.py
Labels: bug, ready for review

#204 Add litellm wrapper
  README.md
  README_ZH.md
  docs/sphinx_doc/en/source/tutorial/203-model.md
  docs/sphinx_doc/zh_CN/source/tutorial/203-model.md
  examples/model_configs_template/litellm_chat_template.json
  setup.py
  src/agentscope/_init.py
  src/agentscope/models/__init__.py
  src/agentscope/models/litellm_model.py
  tests/format_test.py
  tests/litellm_test.py
Labels: enhancement, feature

#221 Add support for vision models in OpenAI Chat API, e.g. gpt-4o, gpt-4-turbo, etc.
  README.md
  README_ZH.md
  docs/sphinx_doc/en/source/tutorial/206-prompt.md
  docs/sphinx_doc/zh_CN/source/tutorial/206-prompt.md
  examples/conversation_with_gpt-4o/README.md
  examples/conversation_with_gpt-4o/conversation_with_gpt-4o.py
  examples/model_configs_template/openai_chat_template.json
  src/agentscope/agents/user_agent.py
  src/agentscope/models/openai_model.py
  src/agentscope/utils/tools.py
  tests/format_test.py
Labels: feature, ready for review

#224 [Hot Fix] Add ImportErrorReporter to optimize the error message when packages are missing
  examples/distributed_simulation/run_simulation.sh
  src/agentscope/agents/rpc_agent.py
  src/agentscope/models/dashscope_model.py
  src/agentscope/rpc/__init__.py
  src/agentscope/rpc/rpc_agent_client.py
  src/agentscope/rpc/rpc_agent_pb2_grpc.py
  src/agentscope/utils/tools.py
Labels: enhancement, ready for review

#203 Make the dictionary parser much more flexible, and decouple task-specific information from DictDialogAgent
  README.md
  README_ZH.md
  docs/sphinx_doc/en/source/tutorial/203-parser.md
  docs/sphinx_doc/en/source/tutorial/advance.rst
  docs/sphinx_doc/zh_CN/source/tutorial/203-parser.md
  docs/sphinx_doc/zh_CN/source/tutorial/advance.rst
  examples/game_werewolf/prompt.py
  examples/game_werewolf/werewolf.py
  examples/game_werewolf/werewolf_utils.py
  src/agentscope/agents/dict_dialog_agent.py
  src/agentscope/agents/react_agent.py
  src/agentscope/message.py
  src/agentscope/parsers/code_block_parser.py
  src/agentscope/parsers/json_object_parser.py
  src/agentscope/parsers/parser_base.py
  src/agentscope/parsers/tagged_content_parser.py
  tests/parser_test.py
Labels: enhancement, feature, ready for review

#232 Doc/litellm doc
  docs/sphinx_doc/en/source/tutorial/206-prompt.md
  docs/sphinx_doc/zh_CN/source/tutorial/206-prompt.md
Labels: documentation

#253 [Hot Fix] Fix import error when import agentscope
  src/agentscope/server/servicer.py
Labels: bug, ready for review

#257 Add a demo video in README.md of both the repo and werewolf game
  README.md
  examples/game_werewolf/README.md
Labels: documentation, ready for review

#266 [HOTFIX] Fix the bug in loguru that cannot display special tags
  src/agentscope/utils/logging_utils.py
  tests/logger_test.py
Labels: bug, ready for review

#267 refine prompt for werewolf games
  examples/game_werewolf/prompt.py
  examples/game_werewolf/werewolf_utils.py
Labels: ready for review
