Repository agentscope-ai/agentscope, pull requests merged in 2024-01, with the labels that each got.

#2 [maintenance] Enhancements to Code Formatting, and Testing Workflowadd workflow
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/release-drafter.yml
  .github/workflows/pre-commit.yml
  .github/workflows/unittest.yml
Labels: enhancement

#7 [DOC] add API reference documentation
  .github/workflows/sphinx_docs.yml
  docs/README.md
  docs/sphinx_doc/Makefile
  docs/sphinx_doc/make.bat
  docs/sphinx_doc/requirements.txt
  docs/sphinx_doc/source/agentscope.agents.rst
  docs/sphinx_doc/source/agentscope.configs.rst
  docs/sphinx_doc/source/agentscope.memory.rst
  docs/sphinx_doc/source/agentscope.models.rst
  docs/sphinx_doc/source/agentscope.pipelines.rst
  docs/sphinx_doc/source/agentscope.rpc.rst
  docs/sphinx_doc/source/agentscope.rst
  docs/sphinx_doc/source/agentscope.service.code.rst
  docs/sphinx_doc/source/agentscope.service.file.rst
  docs/sphinx_doc/source/agentscope.service.retrieval.rst
  docs/sphinx_doc/source/agentscope.service.rst
  docs/sphinx_doc/source/agentscope.service.sql_query.rst
  docs/sphinx_doc/source/agentscope.service.text_processing.rst
  docs/sphinx_doc/source/agentscope.service.web_search.rst
  docs/sphinx_doc/source/agentscope.utils.rst
  docs/sphinx_doc/source/agentscope.web_ui.rst
  docs/sphinx_doc/source/conf.py
  docs/sphinx_doc/source/index.rst
  docs/sphinx_doc/source/tutorial/main.md
  setup.py
Labels: documentation

#6 add jupyter for conversation
  notebook/conversation.ipynb
Labels: documentation

#9 Move defaults and types to constants
  README.md
  docs/sphinx_doc/source/agentscope.rst
  docs/sphinx_doc/source/agentscope.service.rst
  docs/sphinx_doc/source/agentscope.utils.rst
  src/agentscope/__init__.py
  src/agentscope/agents/__init__.py
  src/agentscope/agents/agent.py
  src/agentscope/agents/dialog_agent.py
  src/agentscope/agents/dict_dialog_agent.py
  src/agentscope/agents/operator.py
  src/agentscope/agents/rpc_agent.py
  src/agentscope/agents/rpc_dialog_agent.py
  src/agentscope/configs/model_config.py
  src/agentscope/constants.py
  src/agentscope/file_manager.py
  src/agentscope/models/model.py
  src/agentscope/models/post_model.py
  src/agentscope/pipelines/functional.py
  src/agentscope/pipelines/pipeline.py
  src/agentscope/prompt.py
  src/agentscope/service/__init__.py
  src/agentscope/service/code/exec_python.py
  src/agentscope/service/file/common.py
  src/agentscope/service/file/json.py
  src/agentscope/service/file/text.py
  src/agentscope/service/retrieval/retrieval_from_list.py
  src/agentscope/service/retrieval/similarity.py
  src/agentscope/service/service_response.py
  src/agentscope/service/service_status.py
  src/agentscope/service/sql_query/mongodb.py
  src/agentscope/service/sql_query/mysql.py
  src/agentscope/service/sql_query/sqlite.py
  src/agentscope/service/text_processing/summarization.py
  src/agentscope/service/web_search/search.py
  src/agentscope/utils/common.py
  src/agentscope/utils/enums.py
  tests/operate_file_test.py
  tests/pipeline_test.py
  tests/retrieval_from_list_test.py
  tests/web_search_test.py
Labels: enhancement

#12 add docs for all tutorial
  .github/workflows/sphinx_docs.yml
  docs/sphinx_doc/source/conf.py
  docs/sphinx_doc/source/index.rst
  docs/sphinx_doc/source/tutorial/101-installation.md
  docs/sphinx_doc/source/tutorial/102-concepts.md
  docs/sphinx_doc/source/tutorial/103-example.md
  docs/sphinx_doc/source/tutorial/104-usecase.md
  docs/sphinx_doc/source/tutorial/105-logging.md
  docs/sphinx_doc/source/tutorial/201-agent.md
  docs/sphinx_doc/source/tutorial/202-pipeline.md
  docs/sphinx_doc/source/tutorial/203-model.md
  docs/sphinx_doc/source/tutorial/204-service.md
  docs/sphinx_doc/source/tutorial/205-memory.md
  docs/sphinx_doc/source/tutorial/206-prompt.md
  docs/sphinx_doc/source/tutorial/207-monitor.md
  docs/sphinx_doc/source/tutorial/208-distribute.md
  docs/sphinx_doc/source/tutorial/301-community.md
  docs/sphinx_doc/source/tutorial/302-contribute.md
  docs/sphinx_doc/source/tutorial/advance.rst
  docs/sphinx_doc/source/tutorial/contribute.rst
  docs/sphinx_doc/source/tutorial/main.md
  docs/sphinx_doc/source/tutorial/quick_start.rst
  src/agentscope/pipelines/functional.py
  src/agentscope/prompt.py
  src/agentscope/utils/tools.py
Labels: documentation

#14 [hot fix] Fix import errors in RPC related modules
  src/agentscope/agents/rpc_agent.py
  src/agentscope/message.py
  src/agentscope/rpc/__init__.py
  src/agentscope/rpc/rpc_agent_client.py
Labels: bug

#17 minor improvement for the links and position of "Tutorial"'s first appearance
  README.md
Labels: documentation
