Repository agentscope-ai/agentscope, pull requests merged in 2024-10, with the labels that each got.

#456 Fix ut
  tests/web_search_test.py
Labels: ready for review

#472 [HOTFIX] Fix the error in format function by adding system message
  src/agentscope/models/dashscope_model.py
  src/agentscope/models/litellm_model.py
  src/agentscope/models/model.py
  src/agentscope/models/ollama_model.py
  src/agentscope/models/openai_model.py
  src/agentscope/models/post_model.py
  src/agentscope/models/yi_model.py
  src/agentscope/models/zhipu_model.py
  tests/format_test.py
Labels: bug

#471 use model_dump instead of dict(*) in MarkdownJsonDictParse
  src/agentscope/parsers/json_object_parser.py
Labels: enhancement
