Repository agentscope-ai/agentscope, pull requests merged in 2025-09, with the labels that each got.

#706 Refine tutorial for multi mcp stateful clients
  docs/tutorial/en/src/task_mcp.py
  docs/tutorial/zh_CN/src/task_mcp.py
  examples/agent_deep_research/deep_research_agent.py
  src/agentscope/mcp/_http_stateful_client.py
  src/agentscope/mcp/_stdio_stateful_client.py
Labels: Documentation, Enhancement

#700 Add tutorial for fanout pipeline
  docs/tutorial/en/src/task_model.py
  docs/tutorial/en/src/task_pipeline.py
  docs/tutorial/zh_CN/src/task_model.py
  docs/tutorial/zh_CN/src/task_pipeline.py
  examples/agent_deep_research/README.md
  examples/react_agent/README.md
  examples/workflows/multiagent_conversation/README.md
  examples/workflows/multiagent_debate/README.md
  src/agentscope/tool/_multi_modality/_dashscope_tools.py
  src/agentscope/tool/_multi_modality/_openai_tools.py
Labels: Documentation, Ready for Review, Roadmap, Pipeline

#713 Fix logo size in tutorial
  docs/tutorial/_static/css/gallery.css
Labels: Documentation

#760 fix bug of self._agent_control
  src/agentscope/agent/_react_agent.py
Labels: Bug, Ready for Review, Agent

#736 Fix Gemini formatter local file mime_type from image/* to proper medi…
  src/agentscope/formatter/_gemini_formatter.py
  tests/formatter_gemini_test.py
Labels: Enhancement, Under Review

#781 [HOTFIX] modify the ray import in evaluator
  src/agentscope/evaluate/_evaluator/_ray_evaluator.py
Labels: Bug, Ready for Review

#796 fix(model): 修复DashScopeChatModel enable_thinking 不起作用
  src/agentscope/model/_dashscope_model.py
Labels: Bug, Ready for Review
